"""message

Revision ID: 7792b7d14680
Revises: c4f4e9d27fb5
Create Date: 2026-03-31 11:29:58.656248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7792b7d14680'
down_revision = 'c4f4e9d27fb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'election', ['election_id'], ['id'])

    with op.batch_alter_table('electeur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_voted', sa.Boolean(), nullable=False))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('electeur_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('candidat_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('candidat_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('electeur_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('electeur', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('has_voted')

    with op.batch_alter_table('candidat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('election_id')

    op.drop_table('election')
    # ### end Alembic commands ###
