"""initial schema evoting

Revision ID: c4f4e9d27fb5
Revises: 
Create Date: 2026-03-24 11:33:01.391900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f4e9d27fb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('electeur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electeur_id', sa.Integer(), nullable=True),
    sa.Column('candidat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidat_id'], ['candidat.id'], ),
    sa.ForeignKeyConstraint(['electeur_id'], ['electeur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('electeur')
    op.drop_table('candidat')
    # ### end Alembic commands ###
