"""message

Revision ID: c7bd1acde1cf
Revises: 7792b7d14680
Create Date: 2026-03-31 11:50:49.595917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7bd1acde1cf'
down_revision = '7792b7d14680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electeur', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('has_voted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('electeur_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('candidat_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('candidat_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('electeur_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('electeur', schema=None) as batch_op:
        batch_op.alter_column('has_voted',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
